### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by AlexLardschneider** [maxnowack/homebridge-dht-sensor#15]
Hello,

trying to install this plugin fails with the following error message:

```
pi@raspberrypi:/var/homebridge $ sudo npm install -g homebridge-dht-sensor
npm WARN lifecycle node-dht-sensor@0.0.32~preinstall: cannot run in wd %s %s (wd=%s) node-dht-sensor@0.0.32 ./check-lib.sh /usr/lib/node_modules/.staging/node-dht-sensor-6ba18a77

> node-dht-sensor@0.0.32 install /usr/lib/node_modules/homebridge-dht-sensor/node_modules/node-dht-sensor
> node-gyp configure

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.9.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge-dht-sensor/node_modules/node-dht-sensor/.node-gyp"

> node-dht-sensor@0.0.32 postinstall /usr/lib/node_modules/homebridge-dht-sensor/node_modules/node-dht-sensor
> node-gyp build

make: Entering directory '/usr/lib/node_modules/homebridge-dht-sensor/node_modules/node-dht-sensor/build'
make: *** No rule to make target '../.node-gyp/6.9.1/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/homebridge-dht-sensor/node_modules/node-dht-sensor/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.34-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /usr/lib/node_modules/homebridge-dht-sensor/node_modules/node-dht-sensor
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/usr/lib
└── (empty)

npm ERR! Linux 4.4.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-dht-sensor"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! node-dht-sensor@0.0.32 postinstall: `node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-dht-sensor@0.0.32 postinstall script 'node-gyp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-dht-sensor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-dht-sensor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-dht-sensor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/homebridge/npm-debug.log
npm ERR! code 1
```

**Comment by maxnowack** [comment]
please try to install using the [`--unsafe-perm`](https://docs.npmjs.com/misc/config#unsafe-perm) flag

**Comment by AlexLardschneider** [comment]
Using `--unsafe-perm` did not solve the issue.

**Comment by maxnowack** [comment]
Why do you install the module as root?
This module depends on [node-dht-sensor](https://github.com/momenso/node-dht-sensor) to read the sensor. node-dht-sensor depends on the [BCM2835](http://www.airspayce.com/mikem/bcm2835/) library. Is it installed on your system? If not, install it and try again.
If it's already installed, try to install node-dht-sensor and file an issue on its github repository, since I don't think that your issue is really related to this module

**Comment by AlexLardschneider** [comment]
Well, then how about adding a short guide on how to install this plugin?

Will try that and report back, thanks!

**Comment by maxnowack** [comment]
Yes, you're right. I'll update the readme and include some information about dependencies and how to install it :)

**Comment by AlexLardschneider** [comment]
I tried installing `node-dht-sensor` and `BCM2835`, but it still doesn't install, fails with the same error as above.

**Comment by maxnowack** [comment]
Does `node-dht-sensor` installs without errors?

**Comment by maxnowack** [comment]
This issue is probably related: nodejs/node-gyp#454

**Comment by AlexLardschneider** [comment]
Yes, `node-dht-sensor` installed without errors

**Comment by SteveCohen** [comment]
FWIW I've also had similar permissions problems. In my case node-dht-sensor did NOT install without errors... Nonetheless it'd be great to have a guide. I'd write it myself if I could make it work!

**Comment by DougMidgley** [comment]
`sudo npm install node-dht-sensor --unsafe-perm`  worked for me
